# Generated by Django 4.0.1 on 2022-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profession_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('profession', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Призвание',
                'verbose_name_plural': 'Призвания',
            },
        ),
    ]
