# Generated by Django 4.0.1 on 2022-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('workplace', models.TextField(verbose_name='Где можно работать')),
                ('pay', models.TextField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
